name: nutrilife
description: "NutruLife - Tu asistente nutricional inteligente."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http: ^1.6.0
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 400
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 500
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 600
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 700
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 800
        - asset: assets/fonts/Inter-Variable.ttf
          weight: 900
